version: '3.3'
services:
  discord:
    build:
      context: ./src/services/discord/
    depends_on:
      - rabbitmq
      - api
    restart: unless-stopped
    environment:
      discordToken: ${DISCORD_TOKEN}
      apiToken: ${API_TOKEN}
      rabbitMqHost: rabbitmq
      rabbitMqUser: ${RABBITMQ_USERNAME}
      rabbitMqPW: ${RABBITMQ_PASSWORD}

  api:
    build:
      context: ./process/enrichment-server/
    depends_on:
      - db
    restart: always
    environment:
      rabbitMqHost: rabbitmq_ish
      rabbitMqUser: ${RABBITMQ_USERNAME}
      rabbitMqPW: ${RABBITMQ_PASSWORD}
      apiToken: ${API_TOKEN}
      DBDialect: mariadb
      DBHost: db
      DBDatabase: ish
      DBUser: ish
      DBPassword: ${DB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    # ports:
    #   - "15672:15672" # mgmt port

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ish
      MYSQL_USER: ish
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true

volumes:
  db_data:
